version: '3.8'

services:
  message-handling-application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-handling-application
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - .:/app