version: '3'
services:

  # Development service
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"

  # Production service
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
